export {
  getToken,
  getTeams,
  getCompetitions,
  getMatches,
  getFormation,
  getHeadToHead,
  getEvents,
  getStatistics,
  getCompTable,
  getSinglePlayer,
  getPlayerTransfer,
  getSingleTeam,
  getSquad,
} from "./user";
